/*
 * This code is autogenerated by radioHustleDevTool v1.0.3
 */
/*
 var a = s.split(';');
 for (var i = 0; i < a.length; i++) {
 a[i] = a[i].replace(/\D+\s/gmi, ' ').replace(/w|m$/gmi, '');
 var tmp = a[i].split(' ');
 if (tmp[1] != undefined) {
 switch (tmp[1]) {
 case 'DE':
 tmp[1] = 'Beg';
 break;
 case 'DC':
 tmp[1] = 'RS';
 break;
 case 'CB':
 tmp[1] = 'M';
 break;
 case 'BA':
 tmp[1] = 'S';
 break;
 case 'CBA':
 tmp[1] = 'M+S';
 break;
 }
 }
 }
 */
(function($) {
    var daDates = ['2014-06-08 Beg',
        '2014-06-08 M+S',
        '2014-06-21 Beg',
        '2014-06-21 RS',
        '2014-06-21 M',
        '2014-06-29 Beg',
        '2014-06-29 M+S',
        '2014-07-05 Beg',
        '2014-07-05 RS',
        '2014-07-12 Beg',
        '2014-07-12 RS',
        '2014-07-12 M+S',
        '2014-07-12 Nm',
        '2014-07-12 NV',
        '2014-07-12 I',
        '2014-07-12 Ch',
        '2014-07-12 Pro',
        '2014-07-13 EDC',
        '2014-08-03 Beg',
        '2014-08-03 M+S',
        '2014-08-16 EDC',
        '2014-08-23 Beg',
        '2014-08-30 Beg',
        '2014-08-30 RS',
        '2014-08-30 M+S',
        '2014-08-30 Nm',
        '2014-08-30 NV',
        '2014-08-30 I',
        '2014-08-30 Ch',
        '2014-08-30 Pro',
        '2014-09-06 Beg',
        '2014-09-06 RS',
        '2014-09-06 S',
        '2014-09-20 Beg',
        '2014-09-20 RS',
        '2014-09-20 S',
        '2014-09-20 Pro',
        '2014-09-27 Beg',
        '2014-09-27 M+S',
        '2014-09-27 Beg',
        '2014-10-04 Beg',
        '2014-10-04 RS',
        '2014-10-04 M',
        '2014-10-04 S',
        '2014-10-11 Beg',
        '2014-10-11 RS',
        '2014-10-18 Beg',
        '2014-10-18 RS',
        '2014-10-18 M',
        '2014-10-18 S',
        '2014-10-25 Beg',
        '2014-10-25 RS',
        '2014-10-25 S',
        '2014-10-25 Beg',
        '2014-10-25 RS',
        '2014-10-25 Beg',
        '2014-10-25 RS',
        '2014-11-01 Beg',
        '2014-11-01 M+S',
        '2014-11-08 Beg',
        '2014-11-08 RS',
        '2014-11-08 S',
        '2014-11-08 Beg',
        '2014-11-08 RS',
        '2014-11-08 S',
        '2014-11-15 Beg',
        '2014-11-15 RS',
        '2014-11-22 Beg',
        '2014-11-22 RS',
        '2014-11-22 M',
        '2014-12-07 Beg',
        '2014-12-07 RS',
        '2014-12-07 M',
        '2014-12-07 S',
        '2014-12-07 Beg',
        '2014-12-07 RS',
        '2014-12-14 Beg',
        '2014-12-14 M+S',
        '2014-12-14 Beg',
        '2014-12-14 RS',
        '2015-01-03 Beg',
        '2015-01-03 RS',
        '2015-01-03 M',
        '2015-01-24 Beg',
        '2015-01-24 RS',
        '2015-01-24 M',
        '2015-01-24 S',
        '2015-01-31 Beg',
        '2015-01-31 RS',
        '2015-02-07 Beg',
        '2015-02-07 RS',
        '2015-02-07 M+S',
        '2015-02-14 Beg',
        '2015-02-21 Beg',
        '2015-02-21 RS',
        '2015-02-21 Beg',
        '2015-02-21 RS',
        '2015-02-21 M',
        '2015-02-21 Beg',
        '2015-02-21 RS',
        '2015-02-28 Beg',
        '2015-02-28 RS',
        '2015-02-28 M+S',
        '2015-03-14 Beg',
        '2015-03-14 M+S',
        '2015-03-22 Beg',
        '2015-03-22 RS',
        '2015-03-22 M',
        '2015-03-22 S',
        '2015-03-28 Beg',
        '2015-03-28 RS',
        '2015-03-28 M',
        '2015-03-28 S',
        '2015-03-28 Beg',
        '2015-03-28 RS',
        '2015-04-04 Beg',
        '2015-04-04 M+S',
        '2015-04-04 Beg',
        '2015-04-04 RS',
        '2015-04-11 Beg',
        '2015-04-11 RS',
        '2015-04-11 M',
        '2015-04-11 S',
        '2015-04-18 Beg',
        '2015-04-18 RS',
        '2015-04-18 M+S',
        '2015-04-18 Beg',
        '2015-04-18 M+S',
        '2015-04-25 Beg',
        '2015-04-25 RS',
        '2015-04-25 M',
        '2015-04-25 S',
        '2015-04-26 Beg',
        '2015-05-02 Beg',
        '2015-05-02 RS',
        '2015-05-02 M+S',
        '2015-05-11 Beg',
        '2015-05-11 RS',
        '2015-05-11 M',
        '2015-05-11 S',
        '2015-05-23 Beg',
        '2015-05-23 RS',
        '2015-05-30 Beg',
        '2015-05-30 RS',
        '2015-05-30 M',
        '2015-05-30 S',
        '2015-05-30 Beg',
        '2015-05-30 RS',
        '2015-06-06 Beg',
        '2015-06-06 RS',
        '2015-06-06 M+S',
        '2015-06-13 Beg',
        '2015-06-13 RS',
        '2015-06-13 M+S',
        '2015-06-20 Beg',
        '2015-06-20 RS',
        '2015-06-20 M+S',
        '2015-06-20 Beg',
        '2015-06-20 RS',
        '2015-06-20 M+S',
        '2015-06-27 Beg',
        '2015-06-27 RS',
        '2015-06-27 M+S',
        '2015-07-05 Beg',
        '2015-07-05 RS',
        '2015-07-11 Beg',
        '2015-07-11 RS',
        '2015-07-11 Beg',
        '2015-07-11 RS',
        '2015-07-11 S',
        '2015-07-11 M+S',
        '2015-08-15 Beg',
        '2015-08-15 RS',
        '2015-08-22 Beg',
        '2015-08-22 RS',
        '2015-08-29 Beg',
        '2015-08-29 RS',
        '2015-08-29 M+S',
        '2015-09-05 M',
        '2015-09-05 Pro',
        '2015-09-19 Beg',
        '2015-09-19 RS',
        '2015-09-19 M+S',
        '2015-09-19 Beg',
        '2015-09-19 M+S',
        '2015-09-27 Beg',
        '2015-09-27 RS',
        '2015-10-04 Beg',
        '2015-10-04 RS',
        '2015-10-04 M+S',
        '2015-10-11 Beg',
        '2015-10-11 RS',
        '2015-10-17 Beg',
        '2015-10-24 Beg',
        '2015-10-24 M+S',
        '2015-10-24 Beg',
        '2015-10-24 RS',
        '2015-10-24 M',
        '2015-10-24 S',
        '2015-11-07 Beg',
        '2015-11-07 RS',
        '2015-11-07 M',
        '2015-11-07 S',
        '2015-11-07 Beg',
        '2015-11-07 M+S',
        '2015-11-07 Beg',
        '2015-11-07 M+S',
        '2015-11-15 Beg',
        '2015-11-15 RS',
        '2015-11-21 Beg',
        '2015-11-21 RS',
        '2015-11-21 M+S',
        '2015-11-21 Beg',
        '2015-11-21 RS',
        '2015-11-21 M+S',
        '2015-11-28 Beg',
        '2015-11-28 RS',
        '2015-11-28 M',
        '2015-11-28 S',
        '2015-11-28 Beg',
        '2015-11-28 RS',
        '2015-12-06 Beg',
        '2015-12-06 RS',
        '2015-12-06 M',
        '2015-12-06 S',
        '2015-12-06 Ch',
        '2015-12-12 Beg',
        '2015-12-12 M+S',
        '2015-12-20 Beg',
        '2016-01-05 Beg',
        '2016-01-05 RS',
        '2016-01-05 M+S',
        '2016-01-05 Beg',
        '2016-01-05 RS',
        '2016-01-05 M',
        '2016-01-05 S',
        '2016-01-30 Beg',
        '2016-01-30 RS',
        '2016-01-30 M',
        '2016-01-30 Beg',
        '2016-01-30 RS',
        '2016-02-06 Beg',
        '2016-02-06 Beg',
        '2016-02-06 RS',
        '2016-02-06 M',
        '2016-02-06 S',
        '2016-02-13 Beg',
        '2016-02-13 RS',
        '2016-02-13 Beg',
        '2016-02-13 RS',
        '2016-02-21 Beg',
        '2016-02-21 RS',
        '2016-02-21 M+S',
        '2016-02-27 Beg',
        '2016-02-27 RS',
        '2016-03-05 Beg',
        '2016-03-05 RS',
        '2016-03-05 M',
        '2016-03-05 S',
        '2016-03-12 Beg',
        '2016-03-12 RS',
        '2016-03-12 M+S',
        '2016-03-20 Beg',
        '2016-03-20 RS',
        '2016-03-20 M',
        '2016-03-20 S',
        '2016-03-26 Beg',
        '2016-03-26 RS',
        '2016-03-26 M',
        '2016-03-26 S',
        '2016-04-02 Beg',
        '2016-04-02 RS',
        '2016-04-09 Beg',
        '2016-04-09 RS',
        '2016-04-09 Beg',
        '2016-04-09 RS',
        '2016-04-09 M+S',
        '2016-04-16 Beg',
        '2016-04-16 RS',
        '2016-04-16 M',
        '2016-04-16 S',
        '2016-04-23 Beg',
        '2016-04-23 RS',
        '2016-04-23 M',
        '2016-04-23 S',
        '2016-04-30 Beg',
        '2016-04-30 RS',
        '2016-04-30 M',
        '2016-04-30 S',
        '2016-05-02 Beg',
        '2016-05-02 RS',
        '2016-05-02 M+S',
        '2016-05-07 Beg',
        '2016-05-07 RS',
        '2016-05-07 M+S',
        '2016-05-15 Beg',
        '2016-05-15 RS',
        '2016-05-15 M',
        '2016-05-15 S',
        '2016-05-15 Ch'];

    $.ajaxSetup({
        cache: false
    });

    function wfel() {
        if (window.data != undefined) {
            console.log('done');
            $('#search').show();
            $('#dancer-loading').css('display', 'none');
        } else {
            console.log('test');
            window.setTimeout(function() {
                wfel();
            }, 500);
        }
    }

    wfel();

    function goToByScroll(id) {
        id = id.replace("link", "");
        $('html,body').animate({
                scrollTop: $("#" + id).offset().top
            },
            'slow');
    }



    var pics, links, cl;

    $.ajax({
        url: '/dancers_old/dancers_config.json',
        async: false,
        success: function (data) {
            pics = data.pics;
            links = data.links;
            cl = data.clubs;
        }
    });

    window.onload = function() {
        $.ajax({
            url: '/dancers_old/pages/config.json',
            success: function(data) {
                $('#date-last-competition').html(data.lastCompetition.date);
                $('#link-last-competition').html(data.lastCompetition.name);
                $('#link-last-competition').attr('href', data.lastCompetition.link);
            }
        })
        $('#search').autocomplete({
            source: data,
            select: function(event, ui) {
                $('#search-result').hide({
                    effect: 'blind',
                    complete: function() {
                        $.ajax({
                            url: '/dancers_old/ajax/' + ui.item.value.split(' ')[0] + '.json',
                            type: 'GET',
                            beforeSend: function() {
                                console.log('before load');
                            },
                            success: function(data) {
                                $('#rating-chart').append('<i class="fa fa-3x fa-spin fa-cog" style="text-align: center"></i>');
                                var info = setInfo(data);
                                info.story_dnd = info.story_dnd.map(function(e) {
                                    return e.replace(/\s:\s.*$/gmi, '');
                                });
                                console.dir(info);
                                setAdditionalInfo(data.id);
                                console.log('success');
                                $.ajax({
                                    url: '/dancers_old/da/' + ui.item.value.split(' ')[0].replace(/^0*/gmi, '') + '.txt',
                                    cache: true,
                                    beforeSend: function() {
                                        $('#rating-chart').find('.highcharts-container').remove();
                                    },
                                    success: function(data) {
                                        var id = $('#current-number').html().replace(/^0+/, '');
                                        var labels = [];
                                        var seriesData = function(data) {
                                            data = JSON.parse(data);
                                            var a = [],
                                                k = 0;
                                            for (var i in data) {
                                                if (data.hasOwnProperty(i)) {
                                                    if (data[i] != '') {
                                                        labels.push(daDates[k]);
                                                        a.push(data[i]);
                                                    }
                                                }
                                                k++;
                                            }
                                            console.log(a.length + ' ' + labels.length);
                                            return a;
                                        }(data);
                                        $('#rating-chart').highcharts({
                                            lang: {
                                                printChart: 'Печатать',
                                                downloadPNG: 'Сохранить как PNG',
                                                downloadJPEG: 'Сохранить как JPEG',
                                                downloadPDF: 'Сохранить как PDF',
                                                downloadSVG: 'Сохранить как SVG',
                                                contextButtonTitle: 'Context menu'
                                            },
                                            chart: {
                                                type: 'area'
                                            },
                                            title: {
                                                text: 'График изменения очков Discofox Analytics'
                                            },
                                            credits: {
                                                enabled: false
                                            },
                                            legend: {
                                                enabled: false
                                            },
                                            xAxis: {
                                                categories: labels
                                            },
                                            yAxis: {
                                                title: {
                                                    text: 'Изменения очков'
                                                }
                                            },
                                            series: [{
                                                name: 'Изменения очков',
                                                color: '#7cc7ff',
                                                negativeColor: '#ff7272',
                                                data: seriesData
                                            }]
                                        });
                                    },
                                    complete: function() {
                                        $('#rating-chart').find('i.fa-cog').css('display', 'none');
                                    }
                                });
                            },
                            complete: function() {
                                $('#search-result').show({
                                    effect: 'blind',
                                    complete: function() {
                                        goToByScroll('search-result');
                                    }
                                });
                                console.log('complete');
                            }
                        })
                    }
                });
            },
            minLength: 2
        });
    };

    function setInfo(data) {
        $('#current-number').html(data.id);
        $('#current-name').html(data.name);
        $('#current-club').html((function(s, cl) {
            var w = '';
            var cls = s.split(',');
            for (var i = 0; i < cls.length; i++) {
                var curclub = cls[i].toLowerCase().replace(/\s/gmi, '_');
                console.log(curclub);
                if (cl[curclub] != undefined) {
                    w += '<a href="/clubs/' + cl[curclub] + '/">' + cls[i] + '</a>';
                } else {
                    w += '<a href="/clubs/noname/">' + cls[i] + '</a>';
                }
                if (i != cls.length - 1) {
                    w += ', ';
                }
            }
            return w;
        })(data.club, cl));
        var storyClassic = data.story_classic.split('<br><br>');
        storyClassic = storyClassic.map(function (e) {
            var className = '';
            if (e.indexOf('E') > -1 && e.indexOf('+') > -1) {
                className = 'level-up e-class';
            }
            if (e.indexOf('D') > -1 && e.indexOf('+') > -1) {
                className = 'level-up d-class';
            }
            if (e.indexOf('C') > -1 && e.indexOf('+') > -1) {
                className = 'level-up c-class';
            }
            if (e.indexOf('B') > -1 && e.indexOf('+') > -1) {
                className = 'level-up b-class';
            }
            return '<span class="' + className + '">' + e + '</span>';
        });
        var storyDnD = data.story_dnd.split('<br><br>');
        storyDnD = storyDnD.map(function (e) {
            var className = '';
            if (e.indexOf('Bg') > -1 && e.indexOf('+') > -1) {
                className = 'level-up e-class';
            }
            if (e.indexOf('RS') > -1 && e.indexOf('+') > -1) {
                className = 'level-up d-class';
            }
            if (e.indexOf('M') > -1 && e.indexOf('+') > -1) {
                className = 'level-up c-class';
            }
            if (e.indexOf('RS') == -1 && e.indexOf('S') > -1 && e.indexOf('+') > -1) {
                className = 'level-up b-class';
            }
            return '<span class="' + className + '">' + e + '</span>';
        });
        $('#search-result .story').first().html('История выступления по классике и старой системе ДнД:<br><br>' + storyClassic.join('<br><br>') +
            '<br><br>История выступления по новой системе ДнД:<br><br>' + storyDnD.join('<br><br>'));
        $('.current-class').html(data.class_classic + ' / ' + data.class_dnd);
        $('#current-points-B').html(data.B);
        $('#current-points-C').html(data.C);
        $('#current-points-D').html(data.D);
        $('#current-points-E').html(data.E);
        $('#current-points-S').html(data.S);
        $('#current-points-M').html(data.M);
        $('#current-points-RS').html(data.RS);
        $('#current-points-BG').html(data.Beg);

        return {
            story_dnd: data.story_dnd.split('<br><br>')
        };
    }

    function setAdditionalInfo(id) {
        if (pics.indexOf(id) > -1) {
            $('#pic').attr('src', '/dancers_old/pics/' + id + '.jpg');
            $('.add-avatar-link').remove();
        } else {
            $('#pic').attr('src', '/dancers_old/pics/no_avatar.jpg');
            $('.add-avatar-link').remove();
            $('#pic').parent().append('<span class="add-avatar-link" style="position: absolute; bottom: 25px; font-size: 14px; display: block; margin: 0 auto; width: 200px; border-radius: 25px;text-align: center;"><a href="/payments/avatar">Установить аватар</a></span>');
        }
        if (links.hasOwnProperty(id)) {
            var currentNameSelector = $('#current-name');
            var html = currentNameSelector.html();
            currentNameSelector.html('<a href="' + links[id] + '">' + html + '</a>');
        }
    }
})(jQuery);