/*
 * This code is autogenerated by radioHustleDevTool v1.0.3
 */

/*
 var a = s.split(';');
 for (var i = 0; i < a.length; i++) {
 a[i] = a[i].replace(/\D+\s/gmi, ' ').replace(/w|m$/gmi, '');
 var tmp = a[i].split(' ');
 if (tmp[1] != undefined) {
 switch (tmp[1]) {
 case 'DE':
 tmp[1] = 'Beg';
 break;
 case 'DC':
 tmp[1] = 'RS';
 break;
 case 'CB':
 tmp[1] = 'M';
 break;
 case 'BA':
 tmp[1] = 'S';
 break;
 case 'CBA':
 tmp[1] = 'M+S';
 break;
 }
 }
 }
 */

(function ($) {
    var daDates = ['2014-02-08 ED',
        '2014-02-08 M+S',
        '2014-02-16 ED',
        '2014-02-22 ED',
        '2014-02-22 RS',
        '2014-02-22 M+S',
        '2014-02-22 Nm',
        '2014-02-22 NV',
        '2014-02-22 I',
        '2014-02-22 A',
        '2014-03-01 ED',
        '2014-03-01 RS',
        '2014-03-01 M+S',
        '2014-03-09 ED',
        '2014-03-16 Nm',
        '2014-03-16 NV',
        '2014-03-16 I',
        '2014-03-16 A',
        '2014-03-16 Pro',
        '2014-03-22 ED',
        '2014-03-22 M+S',
        '2014-03-29 ED',
        '2014-03-29 M+S',
        '2014-04-12 ED',
        '2014-04-12 M+S',
        '2014-04-20 Nm',
        '2014-04-20 NV',
        '2014-04-20 I',
        '2014-04-20 A',
        '2014-04-26 Nm',
        '2014-04-26 NV',
        '2014-04-26 I',
        '2014-04-26 A',
        '2014-04-26 Pro',
        '2014-04-27 ED',
        '2014-05-02 EDC',
        '2014-05-02 M+S',
        '2014-05-02 ED',
        '2014-05-02 M+S',
        '2014-05-02 ED',
        '2014-05-02 M+S',
        '2014-05-17 ED',
        '2014-05-17 M',
        '2014-05-17 S',
        '2014-05-24 Nm',
        '2014-05-24 NV',
        '2014-05-24 I',
        '2014-05-24 A',
        '2014-05-31 ED',
        '2014-05-31 RS',
        '2014-05-31 M+S',
        '2014-05-31 Nm',
        '2014-05-31 NV',
        '2014-05-31 I',
        '2014-05-31 A',
        '2014-06-08 ED',
        '2014-06-08 M+S',
        '2014-06-21 ED',
        '2014-06-21 RS',
        '2014-06-21 M',
        '2014-06-29 ED',
        '2014-06-29 M+S',
        '2014-07-05 ED',
        '2014-07-05 RS',
        '2014-07-12 ED',
        '2014-07-12 RS',
        '2014-07-12 M+S',
        '2014-07-12 Nm',
        '2014-07-12 NV',
        '2014-07-12 I',
        '2014-07-12 A',
        '2014-07-12 Pro',
        '2014-07-13 EDC',
        '2014-08-03 ED',
        '2014-08-03 M+S',
        '2014-08-16 EDC',
        '2014-08-23 ED',
        '2014-08-30 ED',
        '2014-08-30 RS',
        '2014-08-30 M+S',
        '2014-08-30 Nm',
        '2014-08-30 NV',
        '2014-08-30 I',
        '2014-08-30 A',
        '2014-08-30 Pro',
        '2014-09-06 ED',
        '2014-09-06 RS',
        '2014-09-06 S',
        '2014-09-20 ED',
        '2014-09-20 RS',
        '2014-09-20 S',
        '2014-09-20 Pro',
        '2014-09-27 ED',
        '2014-09-27 M+S',
        '2014-09-27 ED',
        '2014-10-04 ED',
        '2014-10-04 RS',
        '2014-10-04 M',
        '2014-10-04 S',
        '2014-10-11 ED',
        '2014-10-11 RS',
        '2014-10-18 ED',
        '2014-10-18 RS',
        '2014-10-18 M',
        '2014-10-18 S',
        '2014-10-25 ED',
        '2014-10-25 RS',
        '2014-10-25 S',
        '2014-10-25 ED',
        '2014-10-25 RS',
        '2014-10-25 ED',
        '2014-10-25 RS',
        '2014-11-01 ED',
        '2014-11-01 M+S',
        '2014-11-08 ED',
        '2014-11-08 RS',
        '2014-11-08 S',
        '2014-11-08 ED',
        '2014-11-08 RS',
        '2014-11-08 S',
        '2014-11-15 ED',
        '2014-11-15 RS',
        '2014-11-22 ED',
        '2014-11-22 RS',
        '2014-11-22 M',
        '2014-12-07 ED',
        '2014-12-07 RS',
        '2014-12-07 M',
        '2014-12-07 S',
        '2014-12-07 ED',
        '2014-12-07 RS',
        '2014-12-14 ED',
        '2014-12-14 M+S',
        '2014-12-14 ED',
        '2014-12-14 RS',
        '2015-01-03 ED',
        '2015-01-03 RS',
        '2015-01-03 M',
        '2015-01-24 ED',
        '2015-01-24 RS',
        '2015-01-24 M',
        '2015-01-24 S',
        '2015-01-31 ED',
        '2015-01-31 RS',
        '2015-02-07 ED',
        '2015-02-07 RS',
        '2015-02-07 M+S',
        '2015-02-14 ED',
        '2015-02-21 ED',
        '2015-02-21 RS',
        '2015-02-21 ED',
        '2015-02-21 RS',
        '2015-02-21 M',
        '2015-02-21 ED',
        '2015-02-21 RS',
        '2015-02-28 ED',
        '2015-02-28 RS',
        '2015-02-28 M+S',
        '2015-03-14 ED',
        '2015-03-14 M+S',
        '2015-03-22 ED',
        '2015-03-22 RS',
        '2015-03-22 M',
        '2015-03-22 S',
        '2015-03-28 ED',
        '2015-03-28 RS',
        '2015-03-28 M',
        '2015-03-28 S',
        '2015-03-28 ED',
        '2015-03-28 RS',
        '2015-04-04 ED',
        '2015-04-04 M+S',
        '2015-04-04 ED',
        '2015-04-04 RS',
        '2015-04-11 ED',
        '2015-04-11 RS',
        '2015-04-11 M',
        '2015-04-11 S',
        '2015-04-18 ED',
        '2015-04-18 RS',
        '2015-04-18 M+S',
        '2015-04-18 ED',
        '2015-04-18 M+S',
        '2015-04-25 ED',
        '2015-04-25 RS',
        '2015-04-25 M',
        '2015-04-25 S',
        '2015-04-26 ED',
        '2015-05-02 ED',
        '2015-05-02 RS',
        '2015-05-02 M+S',
        '2015-05-11 ED',
        '2015-05-11 RS',
        '2015-05-11 M',
        '2015-05-11 S',
        '2015-05-23 ED',
        '2015-05-23 RS',
        '2015-05-30 ED',
        '2015-05-30 RS',
        '2015-05-30 M',
        '2015-05-30 S',
        '2015-05-30 ED',
        '2015-05-30 RS',
        '2015-06-06 ED',
        '2015-06-06 RS',
        '2015-06-06 M+S',
        '2015-06-13 ED',
        '2015-06-13 RS',
        '2015-06-13 M+S',
        '2015-06-20 ED',
        '2015-06-20 RS',
        '2015-06-20 M+S',
        '2015-06-20 ED',
        '2015-06-20 RS',
        '2015-06-20 M+S',
        '2015-06-27 ED',
        '2015-06-27 RS',
        '2015-06-27 M+S',
        '2015-07-05 ED',
        '2015-07-05 RS',
        '2015-07-11 ED',
        '2015-07-11 RS',
        '2015-07-11 ED',
        '2015-07-11 RS',
        '2015-07-11 S',
        '2015-07-11 M+S',
        '2015-08-15 ED',
        '2015-08-15 RS',
        '2015-08-22 ED',
        '2015-08-22 RS',
        '2015-08-29 ED',
        '2015-08-29 RS',
        '2015-08-29 M+S',
        '2015-09-05 M',
        '2015-09-05 Pro',
        '2015-09-19 ED',
        '2015-09-19 RS',
        '2015-09-19 M+S',
        '2015-09-19 ED',
        '2015-09-19 M+S',
        '2015-09-27 ED',
        '2015-09-27 RS',
        '2015-10-04 ED',
        '2015-10-04 RS',
        '2015-10-04 M+S',
        '2015-10-11 ED',
        '2015-10-11 RS',
        '2015-10-17 ED',
        '2015-10-24 ED',
        '2015-10-24 M+S',
        '2015-10-24 ED',
        '2015-10-24 RS',
        '2015-10-24 M',
        '2015-10-24 S',
        '2015-11-07 ED',
        '2015-11-07 RS',
        '2015-11-07 M',
        '2015-11-07 S',
        '2015-11-07 ED',
        '2015-11-07 M+S',
        '2015-11-07 ED',
        '2015-11-07 M+S',
        '2015-11-15 ED',
        '2015-11-15 RS',
        '2015-11-21 ED',
        '2015-11-21 RS',
        '2015-11-21 M+S',
        '2015-11-21 ED',
        '2015-11-21 RS',
        '2015-11-21 M+S',
        '2015-11-28 ED',
        '2015-11-28 RS',
        '2015-11-28 M',
        '2015-11-28 S',
        '2015-11-28 ED',
        '2015-11-28 RS',
        '2015-12-06 ED',
        '2015-12-06 RS',
        '2015-12-06 M',
        '2015-12-06 S',
        '2015-12-06 A',
        '2015-12-12 ED',
        '2015-12-12 M+S',
        '2015-12-20 ED',
        '2016-01-05 ED',
        '2016-01-05 RS',
        '2016-01-05 M+S',
        '2016-01-05 ED',
        '2016-01-05 RS',
        '2016-01-05 M',
        '2016-01-05 S',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '2016-01-05 RS',
        '2016-01-05 M',
        '2016-01-05 S'];

    $.ajaxSetup({
        cache: false
    });

    function wfel() {
        if (window.data != undefined) {
            console.log('done');
            $('#search').show();
            $('#dancer-loading').css('display', 'none');
        } else {
            console.log('test');
            window.setTimeout(function () {
                wfel();
            }, 500);
        }
    }

    wfel();

    function goToByScroll(id) {
        id = id.replace("link", "");
        $('html,body').animate({
                scrollTop: $("#" + id).offset().top
            },
            'slow');
    }

    var pics = ['06472', '06776', '04870', '06149', '06274', '06534', '05992', '06887', '06905'];
    var links = {
        '06472': 'http://vk.com/octav',
        '06776': 'http://vk.com/id3348576',
        '04870': 'http://vk.com/id1889472',
        '06149': 'http://vk.com/id137052640',
        '06274': 'http://vk.com/id143710185',
        '06534': 'http://vk.com/id470743',
        '05992': 'http://vk.com/id3808296',
        '06887': 'http://vk.com/id960002',
        '06905': 'http://vk.com/id7270343'
    };
    var cl = {
        'ivara': 'ivara',
        'yes!_(г.саратов)': 'yesds',
        'движение': 'dvizhenie',
        'youdance': 'youdance',
        'open_dance_studio': 'ods',
        'мегаполис': 'megapolis'
    };

    window.onload = function () {
        $('#search').autocomplete({
            source: data,
            select: function (event, ui) {
                $('#search-result').hide({
                    effect: 'blind',
                    complete: function () {
                        $.ajax({
                            url: 'http://radio-hustle.com/dancers_old/ajax/' + ui.item.value.split(' ')[0] + '.json',
                            type: 'GET',
                            beforeSend: function () {
                                console.log('before load');
                            },
                            success: function (data) {
                                $('#rating-chart').append('<i class="fa fa-3x fa-spin fa-cog" style="text-align: center"></i>');
                                var info = setInfo(data);
                                info.story_dnd = info.story_dnd.map(function (e) {
                                    return e.replace(/\s:\s.*$/gmi, '');
                                });
                                console.dir(info);
                                setAdditionalInfo(data.id);
                                console.log('success');
                                $.ajax({
                                    url: 'http://radio-hustle.com/dancers_old/da/' + ui.item.value.split(' ')[0].replace(/^0*/gmi, '') + '.txt',
                                    cache: true,
                                    beforeSend: function () {
                                        $('#rating-chart').find('.highcharts-container').remove();
                                    },
                                    success: function (data) {
                                        var id = $('#current-number').html().replace(/^0+/, '');
                                        var labels = [];
                                        var seriesData = function (data) {
                                            data = JSON.parse(data);
                                            var a = [], k = 0;
                                            for (var i in data) {
                                                if (data.hasOwnProperty(i)) {
                                                    if (data[i] != '') {
                                                        labels.push(daDates[k]);
                                                        a.push(data[i]);
                                                    }
                                                }
                                                k++;
                                            }
                                            console.log(a.length + ' ' + labels.length);
                                            return a;
                                        }(data);
                                        $('#rating-chart').highcharts({
                                            lang: {
                                                printChart: 'Печатать',
                                                downloadPNG: 'Сохранить как PNG',
                                                downloadJPEG: 'Сохранить как JPEG',
                                                downloadPDF: 'Сохранить как PDF',
                                                downloadSVG: 'Сохранить как SVG',
                                                contextButtonTitle: 'Context menu'
                                            },
                                            chart: {
                                                type: 'area'
                                            },
                                            title: {
                                                text: 'График изменения очков Discofox Analytics'
                                            },
                                            credits: {
                                                enabled: false
                                            },
                                            legend: {
                                                enabled: false
                                            },
                                            xAxis: {
                                                categories: labels
                                            },
                                            yAxis: {
                                                title: {
                                                    text: 'Изменения очков'
                                                }
                                            },
                                            series: [{
                                                name: 'Изменения очков',
                                                color: '#7cc7ff',
                                                negativeColor: '#ff7272',
                                                data: seriesData
                                            }]
                                        });
                                    },
                                    complete: function () {
                                        $('#rating-chart').find('i.fa-cog').css('display', 'none');
                                    }
                                });
                            },
                            complete: function () {
                                $('#search-result').show({
                                    effect: 'blind',
                                    complete: function () {
                                        goToByScroll('search-result');
                                    }
                                });
                                console.log('complete');
                            }
                        })
                    }
                });
            },
            minLength: 2
        });
    };

    function setInfo(data) {
        $('#current-number').html(data.id);
        $('#current-name').html(data.name);
        $('#current-club').html((function (s, cl) {
            var w = '';
            var cls = s.split(',');
            for (var i = 0; i < cls.length; i++) {
                var curclub = cls[i].toLowerCase().replace(/\s/gmi, '_');
                console.log(curclub);
                if (cl[curclub] != undefined) {
                    w += '<a href="/clubs/' + cl[curclub] + '/">' + cls[i] + '</a>';
                } else {
                    w += '<a href="/clubs/noname/">' + cls[i] + '</a>';
                }
                if (i != cls.length - 1) {
                    w += ', ';
                }
            }
            return w;
        })(data.club, cl));
        $('#search-result .story').first().html('История выступления по классике и старой системе ДнД:<br><br>' + data.story_classic +
            '<br><br>История выступления по новой системе ДнД:<br><br>' + data.story_dnd);
        $('.current-class').html(data.class_classic + ' / ' + data.class_dnd);
        $('#current-points-B').html(data.B);
        $('#current-points-C').html(data.C);
        $('#current-points-D').html(data.D);
        $('#current-points-E').html(data.E);
        $('#current-points-S').html(data.S);
        $('#current-points-M').html(data.M);
        $('#current-points-RS').html(data.RS);
        $('#current-points-BG').html(data.Beg);

        return {
            story_dnd: data.story_dnd.split('<br><br>')
        };
    }

    function setAdditionalInfo(id) {
        if (pics.indexOf(id) > -1) {
            $('#pic').attr('src', 'http://radio-hustle.com/dancers_old/pics/' + id + '.jpg');
            $('.add-avatar-link').remove();
        } else {
            $('#pic').attr('src', 'http://radio-hustle.com/dancers_old/pics/no_avatar.jpg');
            $('.add-avatar-link').remove();
            $('#pic').parent().append('<span class="add-avatar-link" style="position: absolute; bottom: 25px; font-size: 14px; display: block; margin: 0 auto; width: 200px; border-radius: 25px;text-align: center;"><a href="http://radio-hustle.com/payments/avatar">Установить аватар</a></span>');
        }
        if (links.hasOwnProperty(id)) {
            var currentNameSelector = $('#current-name');
            var html = currentNameSelector.html();
            currentNameSelector.html('<a href="' + links[id] + '">' + html + '</a>');
        }
    }
})(jQuery);