/*
 * This code is autogenerated by radioHustleDevTool v1.0.3
 */

/*
 var a = s.split(';');
 for (var i = 0; i < a.length; i++) {
 a[i] = a[i].replace(/\D+\s/gmi, ' ').replace(/w|m$/gmi, '');
 var tmp = a[i].split(' ');
 if (tmp[1] != undefined) {
 switch (tmp[1]) {
 case 'DE':
 tmp[1] = 'Beg';
 break;
 case 'DC':
 tmp[1] = 'RS';
 break;
 case 'CB':
 tmp[1] = 'M';
 break;
 case 'BA':
 tmp[1] = 'S';
 break;
 case 'CBA':
 tmp[1] = 'M+S';
 break;
 }
 }
 }
 */

(function($) {
    var daDates = [ '2013-10-20RnD Beg',
        '2013-10-26 Beg',
        '2013-10-26 RS+M',
        '2013-10-26 M+S',
        '2013-11-02Kr Beg',
        '2013-11-02Kr M+S',
        '2013-11-09Bar Beg',
        '2013-11-09Bar M+S',
        '2013-11-09 Beg',
        '2013-11-09 RS',
        '2013-11-09 M+S',
        '2013-11-24Spb Beg',
        '2013-11-24Spb RS',
        '2013-11-24Spb Ch',
        '2013-11-30Min Beg',
        '2013-11-30Min RS',
        '2013-11-30Min M+S',
        '2013-11-30Nvs Beg',
        '2013-11-30Nvs M+S',
        '2013-12-08Kr Beg',
        '2013-12-14 Beg',
        '2013-12-14 M',
        '2013-12-14 S',
        '2014-01-04Kr Newcomers',
        '2014-01-04Kr Novice',
        '2014-01-04Kr Intermediate',
        '2014-01-04Kr Ch',
        '2014-01-04Kr Pro',
        '2014-01-18 Newcomers',
        '2014-01-18 Novice',
        '2014-01-18 Intermediate',
        '2014-01-18 Ch',
        '2014-01-18 Pro',
        '2014-01-25 Beg',
        '2014-01-25 M',
        '2014-01-25 S',
        '2014-02-08 Beg',
        '2014-02-08 M+S',
        '2014-02-16Kr Beg',
        '2014-02-22Min Beg',
        '2014-02-22Min RS',
        '2014-02-22Min M+S',
        '2014-02-22Nvs Newcomers',
        '2014-02-22Nvs Novice',
        '2014-02-22Nvs Intermediate',
        '2014-02-22Nvs Ch',
        '2014-03-01 Beg',
        '2014-03-01 RS',
        '2014-03-01 M+S',
        '2014-03-09Kr Beg',
        '2014-03-16Spb Newcomers',
        '2014-03-16Spb Novice',
        '2014-03-16Spb Intermediate',
        '2014-03-16Spb Ch',
        '2014-03-16Spb Pro',
        '2014-03-22Kr Beg',
        '2014-03-22Kr M+S',
        '2014-03-29 Beg',
        '2014-03-29 M+S',
        '2014-04-12 Beg',
        '2014-04-12 M+S',
        '2014-04-20Nvs Newcomers',
        '2014-04-20Nvs Novice',
        '2014-04-20Nvs Intermediate',
        '2014-04-20Nvs Ch',
        '2014-04-26 Newcomers',
        '2014-04-26 Novice',
        '2014-04-26 Intermediate',
        '2014-04-26 Ch',
        '2014-04-26 Pro',
        '2014-04-27Kr Beg',
        '2014-05-02Spb EDC',
        '2014-05-02Spb M+S',
        '2014-05-02Bar Beg',
        '2014-05-02Bar M+S',
        '2014-05-02Ekb Beg',
        '2014-05-02Ekb M+S',
        '2014-05-17 Beg',
        '2014-05-17 M',
        '2014-05-17 S',
        '2014-05-24Spb Newcomers',
        '2014-05-24Spb Novice',
        '2014-05-24Spb Intermediate',
        '2014-05-24Spb Ch',
        '2014-05-31 Beg',
        '2014-05-31 RS',
        '2014-05-31 M+S',
        '2014-05-31Nvs Newcomers',
        '2014-05-31Nvs Novice',
        '2014-05-31Nvs Intermediate',
        '2014-05-31Nvs Ch',
        '2014-06-08Kr Beg',
        '2014-06-08Kr M+S',
        '2014-06-21Min Beg',
        '2014-06-21Min RS',
        '2014-06-21Min M',
        '2014-06-29Spb Beg',
        '2014-06-29Spb M+S',
        '2014-07-05Nvs Beg',
        '2014-07-05Nvs RS',
        '2014-07-12 Beg',
        '2014-07-12 RS',
        '2014-07-12 M+S',
        '2014-07-12Spb Newcomers',
        '2014-07-12Spb Novice',
        '2014-07-12Spb Intermediate',
        '2014-07-12Spb Ch',
        '2014-07-12Spb Pro',
        '2014-07-13Rnd EDC',
        '2014-08-03Spb Beg',
        '2014-08-03Spb M+S',
        '2014-08-16Gel EDC',
        '2014-08-23Spb Beg',
        '2014-08-30Nvs Beg',
        '2014-08-30Nvs RS',
        '2014-08-30Nvs M+S',
        '2014-08-30 Newcomers',
        '2014-08-30 Novice',
        '2014-08-30 Intermediate',
        '2014-08-30 Ch',
        '2014-08-30 Pro',
        '2014-09-06 Beg',
        '2014-09-06 RS',
        '2014-09-06 S',
        '2014-09-20 Beg',
        '2014-09-20 RS',
        '2014-09-20 S',
        '2014-09-20 Pro',
        '2014-09-27Spb Beg',
        '2014-09-27Spb M+S',
        '2014-09-27Kr Beg',
        '2014-10-04 Beg',
        '2014-10-04 RS',
        '2014-10-04 M',
        '2014-10-04 S',
        '2014-10-11Nvs Beg',
        '2014-10-11Nvs RS',
        '2014-10-18Spb Beg',
        '2014-10-18Spb RS',
        '2014-10-18Spb M',
        '2014-10-18Spb S',
        '2014-10-25 Beg',
        '2014-10-25 RS',
        '2014-10-25 S',
        '2014-10-25Kr Beg',
        '2014-10-25Kr RS',
        '2014-10-25Sar Beg',
        '2014-10-25Sar RS',
        '2014-11-01Kr Beg',
        '2014-11-01Kr M+S',
        '2014-11-08 Beg',
        '2014-11-08 RS',
        '2014-11-08 S',
        '2014-11-08Spb Beg',
        '2014-11-08Spb RS',
        '2014-11-08Spb S',
        '2014-11-15Bar Beg',
        '2014-11-15Bar RS',
        '2014-11-22Min Beg',
        '2014-11-22Min RS',
        '2014-11-22Min M',
        '2014-12-07 Beg',
        '2014-12-07 RS',
        '2014-12-07 M',
        '2014-12-07 S',
        '2014-12-07Kr Beg',
        '2014-12-07Kr RS',
        '2014-12-14Nvs Beg',
        '2014-12-14Nvs M+S',
        '2014-12-14Spb Beg',
        '2014-12-14Spb RS',
        '2015-01-03Kr Beg',
        '2015-01-03Kr RS',
        '2015-01-03Kr M',
        '2015-01-24 Beg',
        '2015-01-24 RS',
        '2015-01-24 M',
        '2015-01-24 S',
        '2015-01-31Spb Beg',
        '2015-01-31Spb RS',
        '2015-02-07 Beg',
        '2015-02-07 RS',
        '2015-02-07 M+S',
        '2015-02-14Kr Beg',
        '2015-02-21Nvs Beg',
        '2015-02-21Nvs RS',
        '2015-02-21Min Beg',
        '2015-02-21Min RS',
        '2015-02-21Min M',
        '2015-02-21Spb Beg',
        '2015-02-21Spb RS',
        '2015-02-28 Beg',
        '2015-02-28 RS',
        '2015-02-28 M+S',
        '2015-03-14Kr Beg',
        '2015-03-14Kr M+S',
        '2015-03-22Spb Beg',
        '2015-03-22Spb RS',
        '2015-03-22Spb M',
        '2015-03-22Spb S',
        '2015-03-28 Beg',
        '2015-03-28 RS',
        '2015-03-28 M',
        '2015-03-28 S',
        '2015-03-28Rnd Beg',
        '2015-03-28Rnd RS',
        '2015-04-04Nvs Beg',
        '2015-04-04Nvs M+S',
        '2015-04-04Srt Beg',
        '2015-04-04Srt RS',
        '2015-04-11 Beg',
        '2015-04-11 RS',
        '2015-04-11 M',
        '2015-04-11 S',
        '2015-04-18Spb Beg',
        '2015-04-18Spb RS',
        '2015-04-18Spb M+S',
        '2015-04-18Nvs Beg',
        '2015-04-18Nvs M+S',
        '2015-04-25 Beg',
        '2015-04-25 RS',
        '2015-04-25 M',
        '2015-04-25 S',
        '2015-04-26Kr Beg',
        '2015-05-02Ekb Beg',
        '2015-05-02Ekb RS',
        '2015-05-02Ekb M+S',
        '2015-05-11 Beg',
        '2015-05-11 RS',
        '2015-05-11 M',
        '2015-05-11 S',
        '2015-05-23Spb Beg',
        '2015-05-23Spb RS',
        '2015-05-30 Beg',
        '2015-05-30 RS',
        '2015-05-30 M',
        '2015-05-30 S',
        '2015-05-30Nvs Beg',
        '2015-05-30Nvs RS',
        '2015-06-06Kr Beg',
        '2015-06-06Kr RS',
        '2015-06-06Kr M+S',
        '2015-06-13Spb Beg',
        '2015-06-13Spb RS',
        '2015-06-13Spb M+S',
        '2015-06-20Min Beg',
        '2015-06-20Min RS',
        '2015-06-20Min M+S',
        '2015-06-20Kr Beg',
        '2015-06-20Kr RS',
        '2015-06-20Kr M+S',
        '2015-06-27 Beg',
        '2015-06-27 RS',
        '2015-06-27 M+S',
        '2015-07-05RnD Beg',
        '2015-07-05RnD RS',
        '2015-07-11Nvs Beg',
        '2015-07-11Nvs RS',
        '2015-07-11Spb Beg',
        '2015-07-11Spb RS',
        '2015-07-11Spb S',
        '2015-07-11Spb M+S',
        '2015-08-15Gel Beg',
        '2015-08-15Gel RS',
        '2015-08-22Spb Beg',
        '2015-08-22Spb RS',
        '2015-08-29 Beg',
        '2015-08-29 RS',
        '2015-08-29 M+S',
        '2015-09-05 M',
        '2015-09-05 Pro',
        '2015-09-19 Beg',
        '2015-09-19 RS',
        '2015-09-19 M+S',
        '2015-09-19Nvs Beg',
        '2015-09-19Nvs M+S',
        '2015-09-27Kr Beg',
        '2015-09-27Kr RS',
        '2015-10-04 Beg',
        '2015-10-04 RS',
        '2015-10-04 M+S',
        '2015-10-11Ekb Beg',
        '2015-10-11Ekb RS',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '2015-10-04 Beg',
        '2015-10-04 RS',
        '2015-10-04 M+S' ];

    $.ajaxSetup({
        cache: false
    });

    function wfel() {
        if (window.data != undefined) {
            console.log('done');
            $('#search').show();
            $('#dancer-loading').css('display', 'none');
        } else {
            console.log('test');
            window.setTimeout(function() {
                wfel();
            }, 500);
        }
    }

    wfel();

    function goToByScroll(id) {
        id = id.replace("link", "");
        $('html,body').animate({
                scrollTop: $("#" + id).offset().top
            },
            'slow');
    }

    var pics = ['06472', '06776', '04870', '06149', '06274', '06534', '05992'];
    var links = {
        '06472': 'http://vk.com/octav',
        '06776': 'http://vk.com/id3348576',
        '04870': 'http://vk.com/id1889472',
        '06149': 'http://vk.com/id137052640',
        '06274': 'http://vk.com/id143710185',
        '06534': 'http://vk.com/id470743',
        '05992': 'http://vk.com/id3808296'
    };
    var cl = {
        'ivara': 'ivara',
        'yes!_(г.саратов)': 'yesds',
        'движение': 'dvizhenie',
        'youdance': 'youdance',
        'open_dance_studio': 'ods'
    };

    window.onload = function() {
        $('#search').autocomplete({
            source: data,
            select: function(event, ui) {
                $('#search-result').hide({
                    effect: 'blind',
                    complete: function() {
                        $.ajax({
                            url: 'http://radio-hustle.com/dancers_old/ajax/' + ui.item.value.split(' ')[0] + '.json',
                            type: 'GET',
                            beforeSend: function() {
                                console.log('before load');
                            },
                            success: function(data) {
                                $('#rating-chart').append('<i class="fa fa-3x fa-spin fa-cog" style="text-align: center"></i>');
                                var info = setInfo(data);
                                info.story_dnd = info.story_dnd.map(function (e) {
                                    return e.replace(/\s:\s.*$/gmi, '');
                                });
                                console.dir(info);
                                setAdditionalInfo(data.id);
                                console.log('success');
                                $.ajax({
                                    url: 'http://radio-hustle.com/dancers_old/da/' + ui.item.value.split(' ')[0].replace(/^0*/gmi, '') + '.txt',
                                    cache: true,
                                    beforeSend: function() {
                                        $('#rating-chart').find('.highcharts-container').remove();
                                    },
                                    success: function(data) {
                                        var id = $('#current-number').html().replace(/^0+/, '');
                                        var labels = [];
                                        var seriesData = function(data) {
                                            data = JSON.parse(data);
                                            var a = [], k = 0;
                                            for (var i in data) {
                                                if (data.hasOwnProperty(i)) {
                                                    if (data[i] != '') {
                                                        labels.push(daDates[k]);
                                                        a.push(data[i]);
                                                    }
                                                }
                                                k++;
                                            }
                                            console.log(a.length + ' ' + labels.length);
                                            return a;
                                        }(data);
                                        $('#rating-chart').highcharts({
                                            lang: {
                                                printChart: 'Печатать',
                                                downloadPNG: 'Сохранить как PNG',
                                                downloadJPEG: 'Сохранить как JPEG',
                                                downloadPDF: 'Сохранить как PDF',
                                                downloadSVG: 'Сохранить как SVG',
                                                contextButtonTitle: 'Context menu'
                                            },
                                            chart: {
                                                type: 'area'
                                            },
                                            title: {
                                                text: 'График изменения очков Discofox Analytics'
                                            },
                                            credits: {
                                                enabled: false
                                            },
                                            legend: {
                                                enabled: false
                                            },
                                            xAxis: {
                                                categories: labels
                                            },
                                            yAxis: {
                                                title: {
                                                    text: 'Изменения очков'
                                                }
                                            },
                                            series: [{
                                                name: 'Изменения очков',
                                                color: '#7cc7ff',
                                                negativeColor: '#ff7272',
                                                data: seriesData
                                            }]
                                        });
                                    },
                                    complete: function() {
                                        $('#rating-chart').find('i.fa-cog').css('display', 'none');
                                    }
                                });
                            },
                            complete: function() {
                                $('#search-result').show({
                                    effect: 'blind',
                                    complete: function() {
                                        goToByScroll('search-result');
                                    }
                                });
                                console.log('complete');
                            }
                        })
                    }
                });
            },
            minLength: 2
        });
    };

    function setInfo(data) {
        $('#current-number').html(data.id);
        $('#current-name').html(data.name);
        $('#current-club').html((function(s, cl) {
            var w = '';
            var cls = s.split(',');
            for (var i = 0; i < cls.length; i++) {
                var curclub = cls[i].toLowerCase().replace(/\s/gmi, '_');
                console.log(curclub);
                if (cl[curclub] != undefined) {
                    w += '<a href="/clubs/' + cl[curclub] + '/">' + cls[i] + '</a>';
                } else {
                    w += '<a href="/clubs/noname/">' + cls[i] + '</a>';
                }
                if (i != cls.length - 1) {
                    w += ', ';
                }
            }
            return w;
        })(data.club, cl));
        $('#search-result .story').first().html('История выступления по классике и старой системе ДнД:<br><br>' + data.story_classic +
            '<br><br>История выступления по новой системе ДнД:<br><br>' + data.story_dnd);
        $('.current-class').html(data.class_classic + ' / ' + data.class_dnd);
        $('#current-points-B').html(data.B);
        $('#current-points-C').html(data.C);
        $('#current-points-D').html(data.D);
        $('#current-points-E').html(data.E);
        $('#current-points-S').html(data.S);
        $('#current-points-M').html(data.M);
        $('#current-points-RS').html(data.RS);
        $('#current-points-BG').html(data.Beg);

        return {
            story_dnd: data.story_dnd.split('<br><br>')
        };
    }

    function setAdditionalInfo(id) {
        if (pics.indexOf(id) > -1) {
            $('#pic').attr('src', 'http://radio-hustle.com/dancers_old/pics/' + id + '.jpg');
        } else {
            $('#pic').attr('src', 'http://radio-hustle.com/dancers_old/pics/no_avatar.jpg');
        }
        if (links.hasOwnProperty(id)) {
            var currentNameSelector = $('#current-name');
            var html = currentNameSelector.html();
            currentNameSelector.html('<a href="' + links[id] + '">' + html + '</a>');
        }
    }
})(jQuery);